#+TITLE: Web Development
#+SUBTITLE:  Department of Computer & Information Science, Brooklyn College
#+AUTHOR:    Katherine Chuang
#+EMAIL:     chuang@sci.brooklyn.cuny.edu
#+CREATOR:   katychuang
#+date:      2020-10-28
#+OPTIONS:   H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t ^:nil
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+ALT_TITLE: Lecture Notes

#+HUGO_BASE_DIR: ../hugo/
#+HUGO_SECTION: web
#+HUGO_CATEGORIES: projects web_dev

* Starting a Website
:PROPERTIES:
:EXPORT_FILE_NAME: 0_starting
:EXPORT_DATE: 2020-10-28
:END:

This section focuses on the process, concepts, and tools for building any type of web site or web application. A website has a lot of overlapping functionality and technology as a web application, except it doesn't focus on high volume of dynamism and user interactivity, which would require  a database. This article mentions the two  interchangeable. However, if one were precise, this article focuses on /websites/.

* Process from Idea to Product
:PROPERTIES:
:EXPORT_FILE_NAME: 1_sdlc
:EXPORT_HUGO_SECTION*: process
:EXPORT_TITLE: Process from idea to Product
:NUMBERED: TOC
:END:

Building a website follows many of the principles of building a software application, which includes figuring out what to build ,managing the building, and validating the quality of the final product. In software development this specifica refers to various phases of structured activities such as planning (such as gathering spec requirements), scheduling the work, development, and test.

The name for this set of phases is called /Software development lifecycle (SDLC)/. Some of these phases are described below. It can be customary for your team to cycle through these phases repeatedly.

#+BEGIN_SRC
{{< mermaid>}}
graph LR
 id1(Requirements Gathering) --> B(Design/Specifications) --> C(Scheduling) --> D(Building) --> E(Testing) --> F(Deployment)
{{< /mermaid >}}
#+END_SRC

#+BEGIN_SRC
x
#+END_SRC

** Requirements Gathering- What's the purpose of the website?
:PROPERTIES:
:EXPORT_HUGO_SECTION*: p1
:END:

It helps to know what you're building before you begin building.

Deciding what to build should come from a review of similar websites, as well as discussions with the appropriate stakeholders. For example, if you're building a website for an organization, you shoul devaluate websites from similar organizations, and also speak with the organization.

This is the chance to gather information about the project goals and/or needs, and any must have items. The outcome of this step is a rough list. In the next phase during design, you will further refine the  requirements.

** Design / Specifications - What are you going to build it with and how?
Once you have the general requirements scoped out, it needs to be translated to technical specifications. This includes picking the technologies such the programming language(s), any libraries or frameworks, and so forth. This can also include the stage of creating wireframes, data flow diagrams, and other sketches to describe a roadmap.

** Scheduling - When will it get completed?
Once you figure out what needs to be built with what technology, you need to figure out when you will complete each feature. It helps to make a list of goals for regular intervals, such as weekly. You should keep in mind of any major events or holidays that might cause disruptions, and include them into your plan.

Some teams prefer an /agile/ approach, which means getting a quick prototype produced. Then using that to collect user feedback to guide prioritization of features for future

** Building
This is the execution of the schedule. If you planned well and made the right choices, it will be fairly easy to execute on. One can easily become discouraged during this phase when the project pace doesn't match the scheduled expectations.  It takes a lot of experience to know how to pick the right tool(s) for the job, and estimate tasks accurately, so take all the hiccups in stride as learning experiences.

** Testing - Does it work as expected?
Once you have built your website, be sure to test it. Make a checklist based on the requirements and/or specifications to compare against the item built. Ensure that the website meets all the requirements.

** Deployment - Delivering the software to the client
This is the final stage of the project, when you're ready to deliver the project. With a website this usually means deploying the website to a server.

* Concepts of Web Development
:PROPERTIES:
:EXPORT_FILE_NAME: 2_concepts-of-web-dev
:EXPORT_DATE: 2020-11-12
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :foo bar
:END:

A website is rendered in a web browser through the HTTP Protocol. There's a lot more one should learn about Internet Protocols, but it's not required to get an operational understanding of working with websites.

{{< gslides src="docs.google.com/presentation/d/e/2PACX-1vRnnUJQDcz4FX7jKoUFhxwIXNl664ta3sH5sGmShkeJvfRyu\under{}BMq0N\under{}LyjwutdrHWwsMHkdZUUhSpiX/embed?start=false&amp;loop=false&amp;delayms=3000" >}}

**Web Design Principles**

The page that is rendered by the web browser is formatted in /Hypertext Markup Language/ or HTML for short. HTML is a set of nested tags that describe how the page should be structured. It's like an outline with hierarchical layers or if you recall from data structures class, a tree. This tree is officially called the /Document Object Model (DOM)/.

If we use cake decorating as an analogy, HTML is the structure (i.e. the layers of cake), and /Cascading Style Sheets (CSS)/ is the styling on top of the layers. You can be barebones or go all out with CSS to obscure the underlying layers.

{{< gslides src="docs.google.com/presentation/d/e/2PACX-1vTIl6aclBHsjdDvkfFuDgIQ9esEmw5ue8WsS4m9TyiBO2rTt0DJdhFyZxDrFq9bmuCLN1OVgiSMvXbO/embed?start=false&amp;loop=false&amp;delayms=5000" >}}

Link
Web design is about building blocks
https://www.smashingmagazine.com/web-design-essentials-examples-and-best-practices/

* Tools

** Text editor
You can use any text editor to write these files. Some editors such as VS Code have plugins you can install to help with various web development work.

** Static Site Generators
:PROPERTIES:
EXPORT_HUGO_SECTION*: gp
:END:

Static sites do not have a database backend, "data" is stored in text files. Data is used loosely here to mean contents of the site. Text files can often imply that they are [[https://www.markdownguide.org][markdown]] formatted files.

In order to translate text files into a website in a streamlined manner, you need some sort of tool to /generate/ that website for you. This tool is called a static site generator. There are many Open Source static site generators available to choose from that go by different names. Some are produced in certain programming languages. They tend to require using the command line interface (CLI).

Below describes a couple of options.

** Using Jekyll Static Site Generator

Github Pages recognizes files that are formatted to the Jekyll Static Site Generated fraemwork. Jekyll (https://jekyllrb.com/) is written in the Ruby programming language, it convers text files in markdown format into HTML pages.

Static HTML pages means that it's an HTML page that doesn't change when you view it across different timestaps. As in, static is /not/ a script generated page. The contents do not change because you pull data from a database. A page like that would be considered /dynamic/ because the contents can change.

*** Guides to using Jekyll
The guides and tutorials for using Jekyll are easily found through your nearest search engine. These are some liks:
- https://jekyllrb.com/docs/github-pages/
- Building a static website with Jekyll and GitHub Pages https://programminghistorian.org/en/lessons/building-static-sites-with-jekyll-github-pages

** Using Hugo Static Site Generator

The best reference material is the official documentation at https://gohugo.io

Once you have Hugo installed, make sure your files are organized in their proposed [[https://gohugo.io/getting-started/directory-structure/][directory structure.]] Find a theme, configure your Hugo website.

*** Org-mode with Hugo

This site is generated from the [[https://www.gnu.org/software/emacs/][GNU Emacs]] program under the [[https://orgmode.org][Org Mode.]] In order to use both pieces, you need to use one more open source plugin called [[https://ox-hugo.scripter.co][ox-hugo]]

The contents are contained in ~*.org~ files instead of ~*.markdown~ or ~*.txt~
